name: Readme Generator
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Commit Count
        run: |
          if [ "$(git rev-list main --count)" -gt 1 ]; then
            echo "Project already configured"
            exit 1
          fi

      - name: Generate README.md
        uses: hlinero/readme-template-action@v1
        with:
          token: ${{ secrets.my_pat }}
          template: TEMPLATE.md
          output: README.md

      - name: Commit Changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name "GitHub Action"
            git config user.email "action@github.com"
            git add .
            git commit -m "Auto-update README.md"
            git push
          fi